create table if not exists public.album_stickers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  title text not null check (char_length(title) between 1 and 200),
  image text not null check (image ~ '^https://((images|plus)\.unsplash\.com|images\.pexels\.com)/'),
  kit_name text not null check (char_length(kit_name) between 1 and 200),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists album_stickers_user_id_created_at_idx
  on public.album_stickers (user_id, created_at desc);

grant select on table public.album_stickers to authenticated;

alter table public.album_stickers enable row level security;

drop policy if exists "Users can read their own album stickers" on public.album_stickers;
create policy "Users can read their own album stickers"
  on public.album_stickers
  for select
  to authenticated
  using ((select auth.uid()) = user_id);
